builds:
  -
    ldflags: -s -w -X github.com/bpineau/katafygio/cmd.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64

release:
  # don't autopublish
  draft: true

archive:
  format: binary

changelog:
  filters:
    exclude:
      - Merge

dockers:
  - image: bpineau/katafygio
    goos: linux
    goarch: amd64
    dockerfile: assets/Dockerfile.goreleaser
    tag_templates:
      - '{{ .Tag }}'
      - latest

nfpm:
  name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Arch }}"
  homepage: https://github.com/bpineau/katafygio
  description: Discover and continuously backup Kubernetes objets as yaml files in git
  maintainer: Benjamin Pineau <ben.pineau@gmail.com>
  license: MIT
  vendor: Benjamin Pineau
  formats:
    - deb
    - rpm
  dependencies:
    - git
  replacements:
    amd64: x86_64
