# Goreleaser configuration to build and publish releases on new v* github tags
# (via Github Actions, cf. .github/workflows/release.yml):
# - Build (x86, x86_64, arm64) binaries for Linux, Windows and Mac
# - Build deb and rpm packages
# - Build docker images
# - Publish Github releases (as draft, for manual confirmation)
# - Publish docker images (to docker hub and quay.io)
# - Publish homebrew formula (to https://github.com/bpineau/homebrew-tap)

# Test changes to this file localy with:
#   env HOMEBREW_TAP_GITHUB_TOKEN=fake goreleaser release --rm-dist --skip-publish --skip-sign --skip-validate
# Verify goreleaser upgrades with (cf. https://goreleaser.com/deprecations/):
#   goreleaser check

builds:
  - id: default
    ldflags: -s -w -X github.com/bpineau/katafygio/cmd.version={{.Version}}
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - "386"
    hooks:
      post: make man
  # need for "brews" publisher, that doesn't work with flat binaries (see "archives" below)
  - id: macosx-tarball
    ldflags: -s -w -X github.com/bpineau/katafygio/cmd.version={{.Version}}
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    hooks:
      post: make man

before:
  hooks:
  - go mod download

release:
  # publish github releases as draft, so a human can check and validate
  draft: true

archives:
- id: katafygio
  format: binary
  builds: [default] # publish easy to curl flag files rather than tarballs
- id: macosx-tarball
  builds: [macosx-tarball] # for brews below (needs a tarball)

changelog:
  filters:
    exclude:
      - Merge

dockers:
  # TODO when stable, use "docker_manifest" to publish multi-arch images
  - image_templates:
    - "bpineau/katafygio:latest"
    - "bpineau/katafygio:{{ .Tag }}"
    - "bpineau/katafygio:v{{ .Major }}.{{ .Minor }}"
    - "quay.io/bpineau/katafygio:latest"
    - "quay.io/bpineau/katafygio:{{ .Tag }}"
    - "quay.io/bpineau/katafygio:v{{ .Major }}.{{ .Minor }}"
    goos: linux
    goarch: amd64
    ids: [default]
    dockerfile: assets/Dockerfile.goreleaser
    skip_push: false
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"

nfpms:
-
  file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Arch }}"
  homepage: https://github.com/bpineau/katafygio
  description: Discover and continuously backup Kubernetes objets as yaml files in git
  maintainer: Benjamin Pineau <ben.pineau@gmail.com>
  license: MIT
  bindir: /usr/bin
  vendor: Benjamin Pineau
  formats:
    - deb
    - rpm
  dependencies:
    - git
  contents:
    - src: ./assets/katafygio.yaml
      dst: /etc/katafygio/katafygio.yaml
      type: config
    - src: ./katafygio.8.gz
      dst: /usr/share/man/man8/katafygio.8.gz
  overrides:
    rpm:
      replacements:
        amd64: x86_64
        386: i686
      file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    deb:
      replacements:
        386: i386
      file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

brews:
  - name: katafygio
    ids: [macosx-tarball] # because brews publisher doesn't accept flat binaries

    tap:
      owner: bpineau
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    folder: Formula
    homepage: "https://github.com/bpineau/katafygio"
    description: Discover and continuously backup Kubernetes objets as yaml files in git
    license: MIT
    skip_upload: false

    install: |
      bin.install "katafygio"

    test: |
      system "#{bin}/katafygio version"

