language: go
go:
  - "1.13.x"

# needed for e2e tests (so we can start minikube)
sudo: required
dist: xenial # We need the systemd for the kubeadm and it's default from 16.04+

env:
  global:
    # only needed for e2e tests
    - K8S_VERSION=v1.15.0
    - MINIKUBE_VERSION=v1.2.0
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_HOME=$HOME
    - KUBECONFIG=$HOME/.kube/config

# setup a minikube in travis-ci. only needed for e2e tests
before_script:
  - sudo curl -Lo /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl
  - sudo curl -Lo /usr/local/bin/minikube https://github.com/kubernetes/minikube/releases/download/${MINIKUBE_VERSION}/minikube-linux-amd64
  - sudo chmod +x /usr/local/bin/kubectl /usr/local/bin/minikube
  - mkdir -p $HOME/.kube && touch $HOME/.kube/config
  - sudo -E /usr/local/bin/minikube start --vm-driver=none --kubernetes-version=${K8S_VERSION}
  # Fix the kubectl context, as it is often stale.
  - /usr/local/bin/minikube update-context
  # Wait for Kubernetes to be up and ready.
  - for i in {1..150}; do kubectl get po &> /dev/null && break; sleep 2; done
  - kubectl get ns

install:
  - make tools

script:
  - make install
  - make lint
  - make test
  - make coverall
  - make e2e

