FROM alpine:3.7
RUN apk upgrade --no-cache && \
    apk --no-cache add ca-certificates git openssh-client
RUN install -d -o nobody -g nobody /var/lib/katafygio/data
COPY katafygio /usr/bin/
VOLUME /var/lib/katafygio
USER nobody
ENTRYPOINT ["/usr/bin/katafygio"]
