apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "katafygio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "katafygio.labels.standard" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "katafygio.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
{{ include "katafygio.labels.standard" . | indent 8 }}
    spec:
      securityContext:
        fsGroup: 65534
      serviceAccountName: {{ template "katafygio.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --local-dir={{ .Values.localDir }}
            - --healthcheck-port={{ .Values.healthcheckPort }}
          {{- if .Values.gitTimeout }}
            - --git-timeout={{ .Values.gitTimeout }}
          {{- end }}
          {{- if .Values.gitUrl }}
            - --git-url={{ .Values.gitUrl }}
          {{- end }}
          {{- if .Values.filter }}
            - --filter={{ .Values.filter }}
          {{- end }}
          {{- if .Values.logLevel }}
            - --log-level={{ .Values.logLevel }}
          {{- end }}
          {{- if .Values.logOutput }}
            - --log-output={{ .Values.logOutput }}
          {{- end }}
          {{- if .Values.logServer }}
            - --log-server={{ .Values.logServer }}
          {{- end }}
          {{- if .Values.resyncInterval }}
            - --resync-interval={{ .Values.resyncInterval }}
          {{- end }}
          {{- if .Values.noGit }}
            - --no-git
          {{- end }}
          {{- if .Values.excludeKind }}
            {{- range .Values.excludeKind }}
            - --exclude-kind={{ . }}
            {{- end }}
          {{- end }}
          {{- if .Values.excludeObject }}
            {{- range .Values.excludeObject }}
            - --exclude-object={{ . }}
            {{- end }}
          {{- end }}
          {{- if .Values.gitAuthor }}
            - --git-author={{ .Values.gitAuthor }}
          {{- end }}
          {{- if .Values.gitEmail }}
            - --git-email={{ .Values.gitEmail }}
          {{- end }}
          {{- if .Values.checkInterval }}
            - --check-interval={{ .Values.checkInterval }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.healthcheckPort }}
              protocol: TCP
          livenessProbe:
{{ toYaml .Values.probesDelays.liveness | indent 12 }}
            httpGet:
              path: /health
              port: http
          readinessProbe:
{{ toYaml .Values.probesDelays.readiness | indent 12 }}
            httpGet:
              path: /health
              port: http
          volumeMounts:
            - name: {{ template "katafygio.fullname" . }}-data
              mountPath: {{ .Values.localDir }}
          {{- if and .Values.gitSshKey .Values.gitUrl }}
            - name: katafygio-gitssh
              mountPath: "/.ssh"
              readOnly: true
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        {{- if and .Values.gitSshKey .Values.gitUrl }}
        - name: katafygio-gitssh
          secret:
            secretName: {{ template "katafygio.fullname" . }}
            defaultMode: 256
        {{- end }}
        - name: {{ template "katafygio.fullname" . }}-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "katafygio.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
