name: release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      id: go

    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Log into Docker registries
      run: |
        echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin
        echo "${{ secrets.QUAY_IO_PASSWORD }}" | docker login -u ${{ secrets.QUAY_IO_USERNAME }} --password-stdin quay.io

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2.6.1
      with:
        distribution: goreleaser
        version: v0.172.1
        args: release --rm-dist --skip-sign
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
